mock = [
    {
        "name": "Competitor A",
        "accuracy": "0.8",
        "website": "example.com",
        "description": "asdfasdfasdf",
        "headcount": 0,
        "funding": 100,
        "location": "Paris",
        "category": "",
    },
    {
        "name": "Competitor B",
        "accuracy": "0.55",
        "website": "example.com",
        "description": "asdfasdfasdf",
        "headcount": 0,
        "funding": 100,
        "location": "Paris",
        "category": "",
    },
    {
        "name": "Competitor C",
        "accuracy": "0.67",
        "website": "example.com",
        "description": "asdfasdfasdf",
        "headcount": 0,
        "funding": 100,
        "location": "Paris",
        "category": "",
    },
]
